// Generated by CoffeeScript 1.7.1
(function() {
  var controlTags, each, factory, findControlElements, querySelectorAll,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  factory = function(param, options) {};

  each = Function.prototype.call.bind(Array.prototype.forEach);

  querySelectorAll = function() {
    var el, selector;
    if (arguments[0] instanceof Node) {
      el = arguments[0];
      selector = arguments[1];
    } else {
      el = document;
      selector = arguments[0];
    }
    return Array.prototype.slice.call(el.querySelectorAll(selector));
  };

  controlTags = ["input", "textarea", "button", "select"];

  findControlElements = function(el, accumulator) {
    var _ref;
    if (accumulator == null) {
      accumulator = [];
    }
    if (!el) {
      el = document.body;
    }
    if (_ref = el.tagName.toLowerCase(), __indexOf.call(controlTags, _ref) >= 0) {
      accumulator.push(el);
    } else {
      querySelectorAll(el, controlTags.join(", ")).forEach(function(node) {
        return findControlElements(node, accumulator);
      });
    }
    return accumulator;
  };

}).call(this);
