// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function(root) {
    var Base, CheckableComponent, InputBuilder, InputCollection, InputComponent, InputFactory, SelectComponent, camelize;
    camelize = function(str) {
      var camel;
      camel = str.replace(/(?:^|[-_ ])(\w)/g, function(_, c) {
        if (c) {
          return c.toUpperCase();
        } else {
          return "";
        }
      });
      return camel.charAt(0).toLowerCase() + camel.slice(1);
    };
    Base = (function() {
      function Base(el) {
        this.el = el;
        this.id = el.id;
        this.listeners = [];
        return this;
      }

      Base.prototype.value = function() {
        if (arguments.length) {
          return this._setValue(arguments);
        } else {
          if (this._hasValue() && this.validate()) {
            return this._getValue();
          } else {
            return false;
          }
        }
      };

      Base.prototype.values = function() {
        return this.value(arguments);
      };

      Base.prototype.validate = function() {
        return this.el.checkValidity();
      };

      Base.prototype.isFocused = function() {
        return document.activeElement === this.el;
      };

      Base.prototype._hasValue = function() {
        return !!this.el.value;
      };

      Base.prototype._setValue = function(value) {
        this.dispatchEvent(new Event("change"));
        return (this.el.value = value);
      };

      Base.prototype._getValue = function() {
        return this.el.value;
      };

      Base.prototype._checkable = function() {
        return "checked" in this.el;
      };

      Base.prototype.addEventListener = function(type, listener, useCapture) {
        if (useCapture == null) {
          useCapture = false;
        }
        listener = listener.bind(this);
        this.el.addEventListener(type, listener, useCapture);
        return this.listeners.push({
          type: type,
          listener: listener
        });
      };

      Base.prototype.removeEventListener = function(type, listener, useCapture) {
        if (useCapture == null) {
          useCapture = false;
        }
        this.el.removeEventListener(type, listener, useCapture);
        return listener;
      };

      Base.prototype.dispatchEvent = function(event) {
        return this.el.dispatchEvent(event);
      };

      return Base;

    })();
    InputComponent = (function(_super) {
      __extends(InputComponent, _super);

      function InputComponent(el) {
        InputComponent.__super__.constructor.call(this, el);
      }

      return InputComponent;

    })(Base);
    CheckableComponent = (function(_super) {
      __extends(CheckableComponent, _super);

      function CheckableComponent(el) {
        CheckableComponent.__super__.constructor.call(this, el);
      }

      CheckableComponent.prototype.check = function() {
        return this._switch(true);
      };

      CheckableComponent.prototype.uncheck = function() {
        return this._switch(false);
      };

      CheckableComponent.prototype._switch = function(bool) {
        if (typeof bool === "undefined" || this.isChecked() !== bool) {
          this.el.checked = !this.el.checked;
          this.dispatchEvent(new Event("change"));
        }
        return this.isChecked();
      };

      CheckableComponent.prototype.isChecked = function() {
        return this.el.checked;
      };

      CheckableComponent.prototype.value = function() {
        if (arguments.length) {
          return this._setValue(arguments);
        } else {
          if (this.isChecked()) {
            return CheckableComponent.__super__.value.call(this);
          } else {
            return false;
          }
        }
      };

      return CheckableComponent;

    })(Base);
    SelectComponent = (function(_super) {
      __extends(SelectComponent, _super);

      function SelectComponent(el) {
        SelectComponent.__super__.constructor.call(this, el);
      }

      SelectComponent.prototype.value = function() {
        var option;
        return (function() {
          var _i, _len, _ref, _results;
          _ref = this.selected();
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            option = _ref[_i];
            _results.push(option.value);
          }
          return _results;
        }).call(this);
      };

      SelectComponent.prototype.selected = function() {
        var options;
        options = this.el.querySelectorAll("option");
        return Array.prototype.filter.call(options, function(option) {
          return option.selected && !option.disabled;
        });
      };

      return SelectComponent;

    })(Base);
    InputCollection = (function(_super) {
      __extends(InputCollection, _super);

      function InputCollection(selector) {
        var i, node, nodeList, _i, _len;
        if (selector instanceof NodeList) {
          nodeList = selector;
        } else {
          nodeList = document.querySelectorAll(selector);
        }
        for (i = _i = 0, _len = nodeList.length; _i < _len; i = ++_i) {
          node = nodeList[i];
          this.push(nodeList.item(i));
        }
        return this;
      }

      InputCollection.prototype.push = function(el) {
        if (!(el instanceof Node)) {
          if (jQuery && el instanceof jQuery) {
            el = el[0];
          } else if (typeof el === "string") {
            el = document.querySelector(el);
          } else {
            console.warn("Invalid param passed to InputCollection::push");
            return false;
          }
        }
        return InputCollection.__super__.push.call(this, InputFactory(el));
      };

      InputCollection.prototype.value = function() {
        var input, results, val;
        results = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = this.length; _i < _len; _i++) {
            input = this[_i];
            if (val = input.value()) {
              _results.push(val);
            }
          }
          return _results;
        }).call(this);
        if (results.length) {
          return results;
        } else {
          return false;
        }
      };

      InputCollection.prototype.values = function() {
        return this.value(arguments);
      };

      InputCollection.prototype.hashValue = function() {
        var input, results, val, _i, _len;
        results = {};
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          input = this[_i];
          val = input.value();
          if (val) {
            results[camelize(input.id)] = val;
          }
        }
        if (Object.keys(results).length) {
          return results;
        } else {
          return false;
        }
      };

      InputCollection.prototype.hashValues = function() {
        return this.hashValues(arguments);
      };

      InputCollection.prototype.addEventListener = function(type, listener, useCapture) {
        var input, _i, _len, _results;
        if (useCapture == null) {
          useCapture = false;
        }
        _results = [];
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          input = this[_i];
          _results.push(input.addEventListener(type, listener.bind(this), useCapture));
        }
        return _results;
      };

      InputCollection.prototype.inputById = function(id) {
        var input, _i, _len;
        if (id.charAt(0) === "#") {
          id = id.slice(1);
        }
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          input = this[_i];
          if (input.id === id) {
            return input;
          }
        }
        return false;
      };

      InputCollection.prototype.check = function(param) {
        return this._changeCheck(true, param);
      };

      InputCollection.prototype.uncheck = function(param) {
        return this._changeCheck(false, param);
      };

      InputCollection.prototype._changeCheck = function(onOff, param) {
        var input, _i, _len, _results;
        if (typeof param === "undefined") {
          _results = [];
          for (_i = 0, _len = this.length; _i < _len; _i++) {
            input = this[_i];
            if (input instanceof CheckableComponent) {
              _results.push(input[onOff ? "check" : "uncheck"]());
            }
          }
          return _results;
        } else if (typeof param === "number" && this[param] && this[param]._switch) {
          return this[param][onOff ? "check" : "uncheck"]();
        } else if (typeof param === "string") {
          if ((input = this.inputById(param))) {
            if (input instanceof CheckableComponent) {
              return input[onOff ? "check" : "f"];
            }
          }
        }
      };

      return InputCollection;

    })(Array);
    InputFactory = function(el) {
      var classMatcher, constructor;
      classMatcher = {
        input: {
          radio: CheckableComponent,
          checkbox: CheckableComponent
        },
        select: SelectComponent
      };
      if (typeof el === "string") {
        el = document.querySelectorAll(el);
      }
      if (el.length > 1) {
        return new InputCollection(el);
      } else {
        if (el.item) {
          el = el.item(0);
        }
        switch (el.tagName.toLowerCase()) {
          case "input" || "textarea":
            constructor = classMatcher.input[el.type] || InputComponent;
            return new constructor(el);
          case "select":
            constructor = classMatcher.select;
            return new constructor(el);
          default:
            console.warn("Invalid element passed to InputFactory");
            return false;
        }
      }
    };
    InputBuilder = function(opts) {
      var collection, el, node, nodes, parent, _fn, _i, _j, _len, _len1, _ref;
      parent = (function() {
        if (opts.parent instanceof Node) {
          return opts.parent;
        } else if (jQuery && opts.parent instanceof jQuery) {
          return opts.parent[0];
        } else if (typeof opts.parent === "string") {
          return document.querySelector(opts.parent);
        }
      })();
      nodes = [];
      collection = new InputCollection();
      _ref = opts.els;
      _fn = function() {
        var attr, cl, e, _j, _k, _len1, _len2, _ref1, _ref2;
        e = document.createElement(el.tagName);
        e.id = el.id || "";
        e.name = el.name || "";
        e.textContent = el.textContent || "";
        _ref1 = el.classList;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          cl = _ref1[_j];
          e.classList.add(cl);
        }
        if (el.attr) {
          _ref2 = el.attr;
          for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
            attr = _ref2[_k];
            e.setAttribute(attr.name, attr.val);
          }
        }
        nodes.push(e);
        if (e.tagName === "INPUT") {
          return collection.push(e);
        }
      };
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        el = _ref[_i];
        _fn();
      }
      for (_j = 0, _len1 = nodes.length; _j < _len1; _j++) {
        node = nodes[_j];
        parent.appendChild(node);
      }
      return collection;
    };
    return root.InputClasses = {
      Base: Base,
      InputComponent: InputComponent,
      SelectComponent: SelectComponent,
      CheckableComponent: CheckableComponent,
      InputCollection: InputCollection,
      InputFactory: InputFactory
    };
  })((function() {
    if (typeof exports !== "undefined") {
      return exports;
    } else {
      return window;
    }
  })());

}).call(this);
